version: '3'

services:
  redis_container:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    volumes:
      - /data/data
    restart: always
    networks:
      - auth_network

  mysql_container:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - auth_database:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: authservice
      MYSQL_USER: authservice
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: authservice
    networks:
      - auth_network
  auth_service:
    build:
      context: ./
    ports:
      - "50000:50000"
    restart: always
    networks:
      - aman_network
      - auth_network
    hostname: authentication_service
volumes:
  auth_database:
networks:
  aman_network:
    driver: bridge
    external: true
  auth_network:
    driver: bridge
    internal: true


